# Generated by Django 4.1.1 on 2022-09-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('state', models.CharField(choices=[('new', 'Новая'), ('process', 'В процессе'), ('done', 'Сделано')], default='Новая', max_length=50, verbose_name='Статус')),
                ('date_to_do', models.DateField(null=True, verbose_name='Дата выполнения')),
            ],
        ),
    ]
