# Generated by Django 4.1.1 on 2022-09-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_to_do',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
