# Generated by Django 4.1.1 on 2022-09-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_item_date_to_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description_details',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Подробное описание'),
        ),
    ]
