# Generated by Django 4.1.1 on 2022-09-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_item_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
