# Generated by Django 4.1.1 on 2022-09-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_item_date_to_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_to_do',
            field=models.TextField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
