# Generated by Django 4.1.1 on 2022-10-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_state_type_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.ManyToManyField(related_name='states', to='webapp.state'),
        ),
    ]
