# Generated by Django 4.1.1 on 2022-10-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_task_state_alter_task_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
