# Generated by Django 4.1.1 on 2022-10-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_task_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Дата удаления'),
        ),
    ]
