# Generated by Django 4.1.1 on 2022-10-14 05:47

from django.db import migrations, models
import webapp.models.tasks


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=150, validators=[webapp.models.tasks.unique, webapp.models.tasks.CustomValidator()], verbose_name='Заголовок задачи'),
        ),
    ]
