# Generated by Django 4.1.1 on 2022-11-22 05:03

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.fields.NullBooleanField, related_name='tasks', to='webapp.project', verbose_name='Проект'),
        ),
    ]
